const TEMPLATE = document.createElement('template');
TEMPLATE.innerHTML = `
<style>
@import '/lib/emoji/emoji.css';

    :host {
        padding-left: 50px;
        color: var(--color-grey);
    }

    #emoji-select span{
        padding: 5px;
        width: auto;
        line-height: 30px;
        display: inline-table;
        text-align: center;
        cursor: pointer;
        vertical-align: middle;
        font-size: 28px;
        transition: transform 60ms ease-out;
        transition-delay: 60ms;
    }
    #emoji-select span:hover {
        transition-delay: 0ms;
        transform: scale(1.4);
    }

    #emoji-popover {
        z-index: 5;
        position: absolute;
        left: 30px;
        bottom: 30px;
        border-radius: 30px 30px 30px 30px;
        border: 1px solid var(--color-bg-invert);
        background: var(--color-bg);
        transition-duration: 200ms;
        transition-delay: 0ms;
        transform-style: flat;
        transform-origin: 50% 50% 0;
        opacity: 0;
        transition: all 0.2s linear;
        visibility: hidden;
    }
    #emoji-popover.active{
        visibility: visible;
        opacity:1;
        bottom: 50px;
    }

    .emoji-container {
        width: 20ch;
        height: 20ch;
    }

    .emoji-selector {
        position: absolute;
        top: 5%;
        bottom: 5%;
        overflow-y: scroll;
        text-align: center;
    }
    #picker-button {
        cursor: pointer;
    }
    #picker-button span {
        background-color: var(--color-bg);
        width: 1em;
        height: 1em;
        position: absolute;
        transform:translate(-50%, -50%);
        border: 1px solid var(--color-accent-grey);
        border-radius: 50%;
        font-size: 3em;
    }
</style>


<div id="emoji-popover">
  <div class="emoji-container" id="emoji-container">
    <div class="emoji-selector">
      <div id="emoji-select">
              <span><emoji-grinning-face-with-smiling-eyes></emoji-grinning-face-with-smiling-eyes></span>
              <span><emoji-grinning-face-with-big-eyes></emoji-grinning-face-with-big-eyes></span>
              <span><emoji-beaming-face-with-smiling-eyes></emoji-beaming-face-with-smiling-eyes></span>
              <span><emoji-grinning-face></emoji-grinning-face></span>
              <span><emoji-grinning-squinting-face></emoji-grinning-squinting-face></span>
              <span><emoji-grinning-face-with-sweat></emoji-grinning-face-with-sweat></span>
              <span><emoji-rolling-on-the-floor-laughing></emoji-rolling-on-the-floor-laughing></span>
              <span><emoji-face-with-tears-of-joy></emoji-face-with-tears-of-joy></span>
              <span><emoji-slightly-smiling-face></emoji-slightly-smiling-face></span>
              <span><emoji-upside-down-face></emoji-upside-down-face></span>
              <span><emoji-winking-face></emoji-winking-face></span>
              <span><emoji-smiling-face-with-smiling-eyes></emoji-smiling-face-with-smiling-eyes></span>
              <span><emoji-smiling-face-with-halo></emoji-smiling-face-with-halo></span>
              <span><emoji-smiling-face-with-hearts></emoji-smiling-face-with-hearts></span>
              <span><emoji-smiling-face-with-heart-eyes></emoji-smiling-face-with-heart-eyes></span>
              <span><emoji-star-struck></emoji-star-struck></span>
              <span><emoji-face-blowing-a-kiss></emoji-face-blowing-a-kiss></span>
              <span><emoji-kissing-face></emoji-kissing-face></span>
              <span><emoji-smiling-face></emoji-smiling-face></span>
              <span><emoji-kissing-face-with-closed-eyes></emoji-kissing-face-with-closed-eyes></span>
              <span><emoji-kissing-face-with-smiling-eyes></emoji-kissing-face-with-smiling-eyes></span>
              <span><emoji-smiling-face-with-tear></emoji-smiling-face-with-tear></span>
              <span><emoji-face-savoring-food></emoji-face-savoring-food></span>
              <span><emoji-face-with-tongue></emoji-face-with-tongue></span>
              <span><emoji-winking-face-with-tongue></emoji-winking-face-with-tongue></span>
              <span><emoji-zany-face></emoji-zany-face></span>
              <span><emoji-squinting-face-with-tongue></emoji-squinting-face-with-tongue></span>
              <span><emoji-money-mouth-face></emoji-money-mouth-face></span>
              <span><emoji-hugging-face></emoji-hugging-face></span>
              <span><emoji-face-with-hand-over-mouth></emoji-face-with-hand-over-mouth></span>
              <span><emoji-shushing-face></emoji-shushing-face></span>
              <span><emoji-thinking-face></emoji-thinking-face></span>
              <span><emoji-zipper-mouth-face></emoji-zipper-mouth-face></span>
              <span><emoji-face-with-raised-eyebrow></emoji-face-with-raised-eyebrow></span>
              <span><emoji-neutral-face></emoji-neutral-face></span>
              <span><emoji-expressionless-face></emoji-expressionless-face></span>
              <span><emoji-face-without-mouth></emoji-face-without-mouth></span>
              <span><emoji-smirking-face></emoji-smirking-face></span>
              <span><emoji-unamused-face></emoji-unamused-face></span>
              <span><emoji-face-with-rolling-eyes></emoji-face-with-rolling-eyes></span>
              <span><emoji-grimacing-face></emoji-grimacing-face></span>
              <span><emoji-lying-face></emoji-lying-face></span>
              <span><emoji-relieved-face></emoji-relieved-face></span>
              <span><emoji-pensive-face></emoji-pensive-face></span>
              <span><emoji-sleepy-face></emoji-sleepy-face></span>
              <span><emoji-drooling-face></emoji-drooling-face></span>
              <span><emoji-sleeping-face></emoji-sleeping-face></span>
              <span><emoji-face-with-medical-mask></emoji-face-with-medical-mask></span>
              <span><emoji-face-with-thermometer></emoji-face-with-thermometer></span>
              <span><emoji-face-with-head-bandage></emoji-face-with-head-bandage></span>
              <span><emoji-nauseated-face></emoji-nauseated-face></span>
              <span><emoji-face-vomiting></emoji-face-vomiting></span>
              <span><emoji-sneezing-face></emoji-sneezing-face></span>
              <span><emoji-hot-face></emoji-hot-face></span>
              <span><emoji-cold-face></emoji-cold-face></span>
              <span><emoji-woozy-face></emoji-woozy-face></span>
              <span><emoji-dizzy-face></emoji-dizzy-face></span>
              <span><emoji-exploding-head></emoji-exploding-head></span>
              <span><emoji-cowboy-hat-face></emoji-cowboy-hat-face></span>
              <span><emoji-partying-face></emoji-partying-face></span>
              <span><emoji-disguised-face></emoji-disguised-face></span>
              <span><emoji-smiling-face-with-sunglasses></emoji-smiling-face-with-sunglasses></span>
              <span><emoji-nerd-face></emoji-nerd-face></span>
              <span><emoji-face-with-monocle></emoji-face-with-monocle></span>
              <span><emoji-confused-face></emoji-confused-face></span>
              <span><emoji-worried-face></emoji-worried-face></span>
              <span><emoji-slightly-frowning-face></emoji-slightly-frowning-face></span>
              <span><emoji-frowning-face></emoji-frowning-face></span>
              <span><emoji-face-with-open-mouth></emoji-face-with-open-mouth></span>
              <span><emoji-hushed-face></emoji-hushed-face></span>
              <span><emoji-astonished-face></emoji-astonished-face></span>
              <span><emoji-flushed-face></emoji-flushed-face></span>
              <span><emoji-pleading-face></emoji-pleading-face></span>
              <span><emoji-frowning-face-with-open-mouth></emoji-frowning-face-with-open-mouth></span>
              <span><emoji-anguished-face></emoji-anguished-face></span>
              <span><emoji-fearful-face></emoji-fearful-face></span>
              <span><emoji-anxious-face-with-sweat></emoji-anxious-face-with-sweat></span>
              <span><emoji-sad-but-relieved-face></emoji-sad-but-relieved-face></span>
              <span><emoji-crying-face></emoji-crying-face></span>
              <span><emoji-loudly-crying-face></emoji-loudly-crying-face></span>
              <span><emoji-face-screaming-in-fear></emoji-face-screaming-in-fear></span>
              <span><emoji-confounded-face></emoji-confounded-face></span>
              <span><emoji-persevering-face ></emoji-persevering-face ></span>
              <span><emoji-disappointed-face></emoji-disappointed-face></span>
              <span><emoji-downcast-face-with-sweat></emoji-downcast-face-with-sweat></span>
              <span><emoji-weary-face></emoji-weary-face></span>
              <span><emoji-tired-face></emoji-tired-face></span>
              <span><emoji-yawning-face></emoji-yawning-face></span>
              <span><emoji-face-with-steam-from-nose></emoji-face-with-steam-from-nose></span>
              <span><emoji-pouting-face></emoji-pouting-face></span>
              <span><emoji-angry-face></emoji-angry-face></span>
              <span><emoji-face-with-symbols-on-mouth></emoji-face-with-symbols-on-mouth></span>
              <span><emoji-smiling-face-with-horns></emoji-smiling-face-with-horns></span>
              <span><emoji-angry-face-with-horns></emoji-angry-face-with-horns></span>
              <span><emoji-skull></emoji-skull></span>
              <span><emoji-skull-and-crossbones>☠️</emoji-skull-and-crossbones></span>
              <span><emoji-pile-of-poo></emoji-pile-of-poo></span>
              <span><emoji-clown-face></emoji-clown-face></span>
              <span><emoji-ogre></emoji-ogre></span>
              <span><emoji-goblin></emoji-goblin></span>
              <span><emoji-ghost></emoji-ghost></span>
              <span><emoji-alien></emoji-alien></span>
              <span><emoji-alien-monster></emoji-alien-monster></span>
              <span><emoji-robot></emoji-robot></span>
              <span><emoji-grinning-cat></emoji-grinning-cat></span>
              <span><emoji-grinning-cat-with-smiling-eyes></emoji-grinning-cat-with-smiling-eyes></span>
              <span><emoji-cat-with-tears-of-joy></emoji-cat-with-tears-of-joy></span>
              <span><emoji-smiling-cat-with-heart-eyes></emoji-smiling-cat-with-heart-eyes></span>
              <span><emoji-cat-with-wry-smile></emoji-cat-with-wry-smile></span>
              <span><emoji-kissing-cat></emoji-kissing-cat></span>
              <span><emoji-weary-cat></emoji-weary-cat></span>
              <span><emoji-crying-cat></emoji-crying-cat></span>
              <span><emoji-pouting-cat></emoji-pouting-cat></span>
              <span><emoji-see-no-evil-monkey></emoji-see-no-evil-monkey></span>
              <span><emoji-hear-no-evil-monkey></emoji-hear-no-evil-monkey></span>
              <span><emoji-speak-no-evil-monkey></emoji-speak-no-evil-monkey></span>
              <span><emoji-kiss-mark></emoji-kiss-mark></span>
              <span><emoji-love-letter></emoji-love-letter></span>
              <span><emoji-heart-with-arrow></emoji-heart-with-arrow></span>
              <span><emoji-heart-with-ribbon></emoji-heart-with-ribbon></span>
              <span><emoji-sparkling-heart></emoji-sparkling-heart></span>
              <span><emoji-growing-heart></emoji-growing-heart></span>
              <span><emoji-beating-heart></emoji-beating-heart></span>
              <span><emoji-revolving-hearts></emoji-revolving-hearts></span>
              <span><emoji-two-hearts></emoji-two-hearts></span>
              <span><emoji-heart-decoration></emoji-heart-decoration></span>
              <span><emoji-heart-exclamation>❣️</emoji-heart-exclamation></span>
              <span><emoji-broken-heart></emoji-broken-heart></span>
              <span><emoji-red-heart></emoji-red-heart></span>
              <span><emoji-orange-heart></emoji-orange-heart></span>
              <span><emoji-yellow-heart></emoji-yellow-heart></span>
              <span><emoji-green-heart></emoji-green-heart></span>
              <span><emoji-blue-heart></emoji-blue-heart></span>
              <span><emoji-purple-heart></emoji-purple-heart></span>
              <span><emoji-brown-heart></emoji-brown-heart></span>
              <span><emoji-black-heart></emoji-black-heart></span>
              <span><emoji-white-heart></emoji-white-heart></span>
              <span><emoji-hundred-points></emoji-hundred-points></span>
              <span><emoji-anger-symbol></emoji-anger-symbol></span>
              <span><emoji-collision></emoji-collision></span>
              <span><emoji-dizzy></emoji-dizzy></span>
              <span><emoji-sweat-droplets></emoji-sweat-droplets></span>
              <span><emoji-dashing-away></emoji-dashing-away></span>
              <span><emoji-hole></emoji-hole></span>
              <span><emoji-bomb></emoji-bomb></span>
              <span><emoji-speech-balloon></emoji-speech-balloon></span>
              <span><emoji-left-speech-bubble></emoji-left-speech-bubble></span>
              <span><emoji-right-anger-bubble></emoji-right-anger-bubble></span>
              <span><emoji-thought-balloon></emoji-thought-balloon></span>
              <span><emoji-zzz></emoji-zzz></span>
              <span><emoji-waving-hand></emoji-waving-hand></span>
              <span><emoji-raised-back-of-hand></emoji-raised-back-of-hand></span>
              <span><emoji-hand-with-fingers-splayed></emoji-hand-with-fingers-splayed></span>
              <span><emoji-raised-hand></emoji-raised-hand></span>
              <span><emoji-vulcan-salute></emoji-vulcan-salute></span>
              <span><emoji-ok-hand></emoji-ok-hand></span> 
              <span><emoji-pinched-fingers></emoji-pinched-fingers></span>
              <span><emoji-pinching-hand></emoji-pinching-hand></span>
              <span><emoji-victory-hand></emoji-victory-hand></span>
              <span><emoji-crossed-fingers></emoji-crossed-fingers></span>
              <span><emoji-love-you-gesture></emoji-love-you-gesture></span>
              <span><emoji-sign-of-the-horns></emoji-sign-of-the-horns></span>
              <span><emoji-call-me-hand></emoji-call-me-hand></span>
              <span><emoji-backhand-index-pointing-left></emoji-backhand-index-pointing-left></span>
              <span><emoji-backhand-index-pointing-right></emoji-backhand-index-pointing-right></span>
              <span><emoji-backhand-index-pointing-up></emoji-backhand-index-pointing-up></span>
              <span><emoji-middle-finger></emoji-middle-finger></span>
              <span><emoji-backhand-index-pointing-down></emoji-backhand-index-pointing-down></span>
              <span><emoji-index-pointing-up></emoji-index-pointing-up></span>
              <span><emoji-thumbs-up></emoji-thumbs-up></span>
              <span><emoji-thumbs-down></emoji-thumbs-down></span>
              <span><emoji-raised-fist></emoji-raised-fist></span>
              <span><emoji-oncoming-fist></emoji-oncoming-fist></span>
              <span><emoji-left-facing-fist></emoji-left-facing-fist></span>
              <span><emoji-right-facing-fist></emoji-right-facing-fist></span>
              <span><emoji-clapping-hands></emoji-clapping-hands></span>
              <span><emoji-raising-hands></emoji-raising-hands></span>
              <span><emoji-open-hands></emoji-open-hands></span>
              <span><emoji-palms-up-together></emoji-palms-up-together></span>
              <span><emoji-handshake></emoji-handshake></span>
              <span><emoji-folded-hands></emoji-folded-hands></span>
              <span><emoji-writing-hand></emoji-writing-hand></span>
              <span><emoji-nail-polish></emoji-nail-polish></span>
              <span><emoji-selfie></emoji-selfie></span>
              <span><emoji-flexed-biceps></emoji-flexed-biceps></span>
              <span><emoji-mechanical-arm></emoji-mechanical-arm></span>
              <span><emoji-mechanical-leg></emoji-mechanical-leg></span>
              <span><emoji-leg></emoji-leg></span>
              <span><emoji-foot></emoji-foot></span>
              <span><emoji-ear></emoji-ear></span>
              <span><emoji-ear-with-hearing-aid></emoji-ear-with-hearing-aid></span>
              <span><emoji-nose></emoji-nose></span>
              <span><emoji-brain></emoji-brain></span>
              <span><emoji-anatomical-heart></emoji-anatomical-heart></span>
              <span><emoji-lungs></emoji-lungs></span>
              <span><emoji-tooth></emoji-tooth></span>
              <span><emoji-bone></emoji-bone></span>
              <span><emoji-eyes></emoji-eyes></span>
              <span><emoji-eye></emoji-eye></span>
              <span><emoji-tongue></emoji-tongue></span>
              <span><emoji-mouth></emoji-mouth></span>
              <span><emoji-baby></emoji-baby></span>
              <span><emoji-child></emoji-child></span>
              <span><emoji-boy></emoji-boy></span>
              <span><emoji-girl></emoji-girl></span>
              <span><emoji-person></emoji-person></span>
              <span><emoji-man></emoji-man></span>
              <span><emoji-woman></emoji-woman></span>
              <span><emoji-older-person></emoji-older-person></span>
              <span><emoji-old-man></emoji-old-man></span>
              <span><emoji-old-woman></emoji-old-woman></span>
              <span><emoji-person-frowning></emoji-person-frowning></span>
              <span><emoji-person-pouting></emoji-person-pouting></span>
              <span><emoji-person-gesturing-no></emoji-person-gesturing-no></span>
              <span><emoji-person-gesturing-ok></emoji-person-gesturing-ok></span>
              <span><emoji-person-tipping-hand></emoji-person-tipping-hand></span>
              <span><emoji-person-raising-hand></emoji-person-raising-hand></span>
              <span><emoji-deaf-person></emoji-deaf-person></span>
              <span><emoji-person-bowing></emoji-person-bowing></span>
              <span><emoji-person-facepalming></emoji-person-facepalming></span>
              <span><emoji-person-shrugging></emoji-person-shrugging></span>
              <span><emoji-police-officer></emoji-police-officer></span>
              <span><emoji-detective></emoji-detective></span>
              <span><emoji-guard></emoji-guard></span>
              <span><emoji-ninja></emoji-ninja></span>
              <span><emoji-construction-worker></emoji-construction-worker></span>
              <span><emoji-prince></emoji-prince></span>
              <span><emoji-princess></emoji-princess></span>
              <span><emoji-person-wearing-turban></emoji-person-wearing-turban></span>
              <span><emoji-person-with-skullcap></emoji-person-with-skullcap></span>
              <span><emoji-woman-with-headscarf></emoji-woman-with-headscarf></span>
              <span><emoji-person-in-tuxedo></emoji-person-in-tuxedo></span>
              <span><emoji-person-with-veil></emoji-person-with-veil></span>
              <span><emoji-pregnant-woman></emoji-pregnant-woman></span>
              <span><emoji-breast-feeding></emoji-breast-feeding></span>
              <span><emoji-baby-angel></emoji-baby-angel></span>
              <span><emoji-santa-claus></emoji-santa-claus></span>
              <span><emoji-mrs-claus></emoji-mrs-claus></span>
              <span><emoji-superhero></emoji-superhero></span>
              <span><emoji-supervillain></emoji-supervillain></span>
              <span><emoji-mage></emoji-mage></span>
              <span><emoji-fairy></emoji-fairy></span>
              <span><emoji-vampire></emoji-vampire></span>
              <span><emoji-merperson></emoji-merperson></span>
              <span><emoji-elf></emoji-elf></span>
              <span><emoji-genie></emoji-genie></span>
              <span><emoji-zombie></emoji-zombie></span>
              <span><emoji-person-getting-massage></emoji-person-getting-massage></span>
              <span><emoji-person-getting-haircut></emoji-person-getting-haircut></span>
              <span><emoji-person-walking></emoji-person-walking></span>
              <span><emoji-person-standing></emoji-person-standing></span>
              <span><emoji-person-kneeling></emoji-person-kneeling></span>
              <span><emoji-person-running></emoji-person-running></span>
              <span><emoji-woman-dancing></emoji-woman-dancing></span>
              <span><emoji-man-dancing></emoji-man-dancing></span>
              <span><emoji-person-in-suit-levitating></emoji-person-in-suit-levitating></span>
              <span><emoji-people-with-bunny-ears></emoji-people-with-bunny-ears></span>
              <span><emoji-person-in-steamy-room></emoji-person-in-steamy-room></span>
              <span><emoji-person-climbing></emoji-person-climbing></span>
              <span><emoji-person-fencing></emoji-person-fencing></span>
              <span><emoji-horse-racing></emoji-horse-racing></span>
              <span><emoji-skier></emoji-skier></span>
              <span><emoji-snowboarder></emoji-snowboarder></span>
              <span><emoji-person-golfing></emoji-person-golfing></span>
              <span><emoji-person-surfing></emoji-person-surfing></span>
              <span><emoji-person-rowing-boat></emoji-person-rowing-boat></span>
              <span><emoji-person-swimming></emoji-person-swimming></span>
              <span><emoji-person-bouncing-ball></emoji-person-bouncing-ball></span>
              <span><emoji-person-lifting-weights></emoji-person-lifting-weights></span>
              <span><emoji-person-biking></emoji-person-biking></span>
              <span><emoji-person-mountain-biking></emoji-person-mountain-biking></span>
              <span><emoji-person-cartwheeling></emoji-person-cartwheeling></span>
              <span><emoji-people-wrestling></emoji-people-wrestling></span>
              <span><emoji-person-playing-water-polo></emoji-person-playing-water-polo></span>
              <span><emoji-person-playing-handball></emoji-person-playing-handball></span>
              <span><emoji-person-juggling></emoji-person-juggling></span>
              <span><emoji-person-in-lotus-position></emoji-person-in-lotus-position></span>
              <span><emoji-person-taking-bath></emoji-person-taking-bath></span>
              <span><emoji-person-in-bed></emoji-person-in-bed></span>
              <span><emoji-women-holding-hands></emoji-women-holding-hands></span>
              <span><emoji-woman-and-man-holding-hands></emoji-woman-and-man-holding-hands></span>
              <span><emoji-men-holding-hands></emoji-men-holding-hands></span>
              <span><emoji-kiss></emoji-kiss></span>
              <span><emoji-couple-with-heart></emoji-couple-with-heart></span>
              <span><emoji-family></emoji-family></span>
              <span><emoji-speaking-head></emoji-speaking-head></span>
              <span><emoji-bust-in-silhouette></emoji-bust-in-silhouette></span>
              <span><emoji-busts-in-silhouette></emoji-busts-in-silhouette></span>
              <span><emoji-people-hugging></emoji-people-hugging></span>
              <span><emoji-footprints></emoji-footprints></span>
              <span><emoji-monkey-face></emoji-monkey-face></span>
              <span><emoji-monkey></emoji-monkey></span>
              <span><emoji-gorilla></emoji-gorilla></span>
              <span><emoji-orangutan></emoji-orangutan></span>
              <span><emoji-dog-face></emoji-dog-face></span>
              <span><emoji-dog></emoji-dog></span>
              <span><emoji-guide-dog></emoji-guide-dog></span>
              <span><emoji-poodle></emoji-poodle></span>
              <span><emoji-wolf></emoji-wolf></span>
              <span><emoji-fox></emoji-fox></span>
              <span><emoji-raccoon></emoji-raccoon></span>
              <span><emoji-cat-face></emoji-cat-face></span>
              <span><emoji-cat></emoji-cat></span>
              <span><emoji-lion></emoji-lion></span>
              <span><emoji-tiger-face></emoji-tiger-face></span>
              <span><emoji-tiger></emoji-tiger></span>
              <span><emoji-leopard></emoji-leopard></span>
              <span><emoji-horse-face></emoji-horse-face></span>
              <span><emoji-horse></emoji-horse></span>
              <span><emoji-unicorn></emoji-unicorn></span>
              <span><emoji-zebra></emoji-zebra></span>
              <span><emoji-deer></emoji-deer></span>
              <span><emoji-bison></emoji-bison></span>
              <span><emoji-cow-face></emoji-cow-face></span>
              <span><emoji-ox></emoji-ox></span>
              <span><emoji-water-buffalo></emoji-water-buffalo></span>
              <span><emoji-cow></emoji-cow></span>
              <span><emoji-pig-face></emoji-pig-face></span>
              <span><emoji-pig></emoji-pig></span>
              <span><emoji-boar></emoji-boar></span>
              <span><emoji-pig-nose></emoji-pig-nose></span>
              <span><emoji-ram></emoji-ram></span>
              <span><emoji-ewe></emoji-ewe></span>
              <span><emoji-goat></emoji-goat></span>
              <span><emoji-camel></emoji-camel></span>
              <span><emoji-two-hump-camel></emoji-two-hump-camel></span>
              <span><emoji-llama></emoji-llama></span>
              <span><emoji-giraffe></emoji-giraffe></span>
              <span><emoji-elephant></emoji-elephant></span>
              <span><emoji-mammoth></emoji-mammoth></span>
              <span><emoji-rhinoceros></emoji-rhinoceros></span>
              <span><emoji-hippopotamus></emoji-hippopotamus></span>
              <span><emoji-mouse-face></emoji-mouse-face></span>
              <span><emoji-mouse></emoji-mouse></span>
              <span><emoji-rat></emoji-rat></span>
              <span><emoji-hamster></emoji-hamster></span>
              <span><emoji-rabbit-face></emoji-rabbit-face></span>
              <span><emoji-rabbit></emoji-rabbit></span>
              <span><emoji-chipmunk></emoji-chipmunk></span>
              <span><emoji-beaver></emoji-beaver></span>
              <span><emoji-hedgehog></emoji-hedgehog></span>
              <span><emoji-bat></emoji-bat></span>
              <span><emoji-bear></emoji-bear></span>
              <span><emoji-koala></emoji-koala></span>
              <span><emoji-panda></emoji-panda></span>
              <span><emoji-sloth></emoji-sloth></span>
              <span><emoji-otter></emoji-otter></span>
              <span><emoji-skunk></emoji-skunk></span>
              <span><emoji-kangaroo></emoji-kangaroo></span>
              <span><emoji-badger></emoji-badger></span>
              <span><emoji-paw-prints></emoji-paw-prints></span>
              <span><emoji-turkey></emoji-turkey></span>
              <span><emoji-chicken></emoji-chicken></span>
              <span><emoji-rooster></emoji-rooster></span>
              <span><emoji-hatching-chick></emoji-hatching-chick></span>
              <span><emoji-baby-chick></emoji-baby-chick></span>
              <span><emoji-front-facing-baby-chick></emoji-front-facing-baby-chick></span>
              <span><emoji-bird></emoji-bird></span>
              <span><emoji-penguin></emoji-penguin></span>
              <span><emoji-dove></emoji-dove></span>
              <span><emoji-eagle></emoji-eagle></span>
              <span><emoji-duck></emoji-duck></span>
              <span><emoji-swan></emoji-swan></span>
              <span><emoji-owl></emoji-owl></span>
              <span><emoji-dodo></emoji-dodo></span>
              <span><emoji-feather></emoji-feather></span>
              <span><emoji-flamingo></emoji-flamingo></span>
              <span><emoji-peacock></emoji-peacock></span>
              <span><emoji-parrot></emoji-parrot></span>
              <span><emoji-frog></emoji-frog></span>
              <span><emoji-crocodile></emoji-crocodile></span>
              <span><emoji-turtle></emoji-turtle></span>
              <span><emoji-lizard></emoji-lizard></span>
              <span><emoji-snake></emoji-snake></span>
              <span><emoji-dragon-face></emoji-dragon-face></span>
              <span><emoji-dragon></emoji-dragon></span>
              <span><emoji-sauropod></emoji-sauropod></span>
              <span><emoji-t-rex></emoji-t-rex></span>
              <span><emoji-spouting-whale></emoji-spouting-whale></span>
              <span><emoji-whale></emoji-whale></span>
              <span><emoji-dolphin></emoji-dolphin></span>
              <span><emoji-seal></emoji-seal></span>
              <span><emoji-fish></emoji-fish></span>
              <span><emoji-tropical-fish></emoji-tropical-fish></span>
              <span><emoji-blowfish></emoji-blowfish></span>
              <span><emoji-shark></emoji-shark></span>
              <span><emoji-octopus></emoji-octopus></span>
              <span><emoji-spiral-shell></emoji-spiral-shell></span>
              <span><emoji-snail></emoji-snail></span>
              <span><emoji-butterfly></emoji-butterfly></span>
              <span><emoji-bug></emoji-bug></span>
              <span><emoji-ant></emoji-ant></span>
              <span><emoji-honeybee></emoji-honeybee></span>
              <span><emoji-beetle></emoji-beetle></span>
              <span><emoji-lady-beetle></emoji-lady-beetle></span>
              <span><emoji-cricket></emoji-cricket></span>
              <span><emoji-cockroach></emoji-cockroach></span>
              <span><emoji-spider></emoji-spider></span>
              <span><emoji-spider-web></emoji-spider-web></span>
              <span><emoji-scorpion></emoji-scorpion></span>
              <span><emoji-mosquito></emoji-mosquito></span>
              <span><emoji-fly></emoji-fly></span>
              <span><emoji-worm></emoji-worm></span>
              <span><emoji-microbe></emoji-microbe></span>
              <span><emoji-bouquet></emoji-bouquet></span>
              <span><emoji-cherry-blossom></emoji-cherry-blossom></span>
              <span><emoji-white-flower></emoji-white-flower></span>
              <span><emoji-rosette></emoji-rosette></span>
              <span><emoji-rose></emoji-rose></span>
              <span><emoji-wilted-flower></emoji-wilted-flower></span>
              <span><emoji-hibiscus></emoji-hibiscus></span>
              <span><emoji-sunflower></emoji-sunflower></span>
              <span><emoji-blossom></emoji-blossom></span>
              <span><emoji-tulip></emoji-tulip></span>
              <span><emoji-seedling></emoji-seedling></span>
              <span><emoji-potted-plant></emoji-potted-plant></span>
              <span><emoji-evergreen-tree></emoji-evergreen-tree></span>
              <span><emoji-deciduous-tree></emoji-deciduous-tree></span>
              <span><emoji-palm-tree></emoji-palm-tree></span>
              <span><emoji-cactus></emoji-cactus></span>
              <span><emoji-sheaf-of-rice></emoji-sheaf-of-rice></span>
              <span><emoji-herb></emoji-herb></span>
              <span><emoji-shamrock></emoji-shamrock></span>
              <span><emoji-four-leaf-clover></emoji-four-leaf-clover></span>
              <span><emoji-maple-leaf></emoji-maple-leaf></span>
              <span><emoji-fallen-leaf></emoji-fallen-leaf></span>
              <span><emoji-leaf-fluttering-in-wind></emoji-leaf-fluttering-in-wind></span>
              <span><emoji-grapes></emoji-grapes></span>
              <span><emoji-melon></emoji-melon></span>
              <span><emoji-watermelon></emoji-watermelon></span>
              <span><emoji-tangerine></emoji-tangerine></span>
              <span><emoji-lemon></emoji-lemon></span>
              <span><emoji-banana></emoji-banana></span>
              <span><emoji-pineapple></emoji-pineapple></span>
              <span><emoji-mango></emoji-mango></span>
              <span><emoji-red-apple></emoji-red-apple></span>
              <span><emoji-green-apple></emoji-green-apple></span>
              <span><emoji-pear></emoji-pear></span>
              <span><emoji-peach></emoji-peach></span>
              <span><emoji-cherries></emoji-cherries></span>
              <span><emoji-strawberry></emoji-strawberry></span>
              <span><emoji-blueberries></emoji-blueberries></span>
              <span><emoji-kiwi-fruit></emoji-kiwi-fruit></span>
              <span><emoji-tomato></emoji-tomato></span>
              <span><emoji-olive></emoji-olive></span>
              <span><emoji-coconut></emoji-coconut></span>
              <span><emoji-avocado></emoji-avocado></span>
              <span><emoji-eggplant></emoji-eggplant></span>
              <span><emoji-potato></emoji-potato></span>
              <span><emoji-carrot></emoji-carrot></span>
              <span><emoji-ear-of-corn></emoji-ear-of-corn></span>
              <span><emoji-hot-pepper></emoji-hot-pepper></span>
              <span><emoji-bell-pepper></emoji-bell-pepper></span>
              <span><emoji-cucumber></emoji-cucumber></span>
              <span><emoji-leafy-green></emoji-leafy-green></span>
              <span><emoji-broccoli></emoji-broccoli></span>
              <span><emoji-garlic></emoji-garlic></span>
              <span><emoji-onion></emoji-onion></span>
              <span><emoji-mushroom></emoji-mushroom></span>
              <span><emoji-peanuts></emoji-peanuts></span>
              <span><emoji-chestnut></emoji-chestnut></span>
              <span><emoji-bread></emoji-bread></span>
              <span><emoji-croissant></emoji-croissant></span>
              <span><emoji-baguette-bread></emoji-baguette-bread></span>
              <span><emoji-flatbread></emoji-flatbread></span>
              <span><emoji-pretzel></emoji-pretzel></span>
              <span><emoji-bagel></emoji-bagel></span>
              <span><emoji-pancakes></emoji-pancakes></span>
              <span><emoji-waffle></emoji-waffle></span>
              <span><emoji-cheese-wedge></emoji-cheese-wedge></span>
              <span><emoji-meat-on-bone></emoji-meat-on-bone></span>
              <span><emoji-poultry-leg></emoji-poultry-leg></span>
              <span><emoji-cut-of-meat></emoji-cut-of-meat></span>
              <span><emoji-bacon></emoji-bacon></span>
              <span><emoji-hamburger></emoji-hamburger></span>
              <span><emoji-french-fries></emoji-french-fries></span>
              <span><emoji-pizza></emoji-pizza></span>
              <span><emoji-hot-dog></emoji-hot-dog></span>
              <span><emoji-sandwich></emoji-sandwich></span>
              <span><emoji-taco></emoji-taco></span>
              <span><emoji-burrito></emoji-burrito></span>
              <span><emoji-tamale></emoji-tamale></span>
              <span><emoji-stuffed-flatbread></emoji-stuffed-flatbread></span>
              <span><emoji-falafel></emoji-falafel></span>
              <span><emoji-egg></emoji-egg></span>
              <span><emoji-cooking></emoji-cooking></span>
              <span><emoji-shallow-pan-of-food></emoji-shallow-pan-of-food></span>
              <span><emoji-pot-of-food></emoji-pot-of-food></span>
              <span><emoji-fondue></emoji-fondue></span>
              <span><emoji-bowl-with-spoon></emoji-bowl-with-spoon></span>
              <span><emoji-green-salad></emoji-green-salad></span>
              <span><emoji-popcorn></emoji-popcorn></span>
              <span><emoji-butter></emoji-butter></span>
              <span><emoji-salt></emoji-salt></span>
              <span><emoji-canned-food></emoji-canned-food></span>
              <span><emoji-bento-box></emoji-bento-box></span>
              <span><emoji-rice-cracker></emoji-rice-cracker></span>
              <span><emoji-rice-ball></emoji-rice-ball></span>
              <span><emoji-cooked-rice></emoji-cooked-rice></span>
              <span><emoji-curry-rice></emoji-curry-rice></span>
              <span><emoji-steaming-bowl></emoji-steaming-bowl></span>
              <span><emoji-spaghetti></emoji-spaghetti></span>
              <span><emoji-roasted-sweet-potato></emoji-roasted-sweet-potato></span>
              <span><emoji-oden></emoji-oden></span>
              <span><emoji-sushi></emoji-sushi></span>
              <span><emoji-fried-shrimp></emoji-fried-shrimp></span>
              <span><emoji-fish-cake-with-swirl></emoji-fish-cake-with-swirl></span>
              <span><emoji-moon-cake></emoji-moon-cake></span>
              <span><emoji-dango></emoji-dango></span>
              <span><emoji-dumpling></emoji-dumpling></span>
              <span><emoji-fortune-cookie></emoji-fortune-cookie></span>
              <span><emoji-takeout-box></emoji-takeout-box></span>
              <span><emoji-crab></emoji-crab></span>
              <span><emoji-lobster></emoji-lobster></span>
              <span><emoji-shrimp></emoji-shrimp></span>
              <span><emoji-squid></emoji-squid></span>
              <span><emoji-oyster></emoji-oyster></span>
              <span><emoji-soft-ice-cream></emoji-soft-ice-cream></span>
              <span><emoji-shaved-ice></emoji-shaved-ice></span>
              <span><emoji-ice-cream></emoji-ice-cream></span>
              <span><emoji-doughnut></emoji-doughnut></span>
              <span><emoji-cookie></emoji-cookie></span>
              <span><emoji-birthday-cake></emoji-birthday-cake></span>
              <span><emoji-shortcake></emoji-shortcake></span>
              <span><emoji-cupcake></emoji-cupcake></span>
              <span><emoji-pie></emoji-pie></span>
              <span><emoji-chocolate-bar></emoji-chocolate-bar></span>
              <span><emoji-candy></emoji-candy></span>
              <span><emoji-lollipop></emoji-lollipop></span>
              <span><emoji-custard></emoji-custard></span>
              <span><emoji-honey-pot></emoji-honey-pot></span>
              <span><emoji-baby-bottle></emoji-baby-bottle></span>
              <span><emoji-glass-of-milk></emoji-glass-of-milk></span>
              <span><emoji-hot-beverage></emoji-hot-beverage></span>
              <span><emoji-teapot></emoji-teapot></span>
              <span><emoji-teacup-without-handle></emoji-teacup-without-handle></span>
              <span><emoji-sake></emoji-sake></span>
              <span><emoji-bottle-with-popping-cork></emoji-bottle-with-popping-cork></span>
              <span><emoji-wine-glass></emoji-wine-glass></span>
              <span><emoji-cocktail-glass></emoji-cocktail-glass></span>
              <span><emoji-tropical-drink></emoji-tropical-drink></span>
              <span><emoji-beer-mug></emoji-beer-mug></span>
              <span><emoji-clinking-beer-mugs></emoji-clinking-beer-mugs></span>
              <span><emoji-clinking-glasses></emoji-clinking-glasses></span>
              <span><emoji-tumbler-glass></emoji-tumbler-glass></span>
              <span><emoji-cup-with-straw></emoji-cup-with-straw></span>
              <span><emoji-bubble-tea></emoji-bubble-tea></span>
              <span><emoji-beverage-box></emoji-beverage-box></span>
              <span><emoji-mate></emoji-mate></span>
              <span><emoji-ice></emoji-ice></span>
              <span><emoji-chopsticks></emoji-chopsticks></span>
              <span><emoji-fork-and-knife-with-plate></emoji-fork-and-knife-with-plate></span>
              <span><emoji-fork-and-knife></emoji-fork-and-knife></span>
              <span><emoji-spoon></emoji-spoon></span>
              <span><emoji-kitchen-knife></emoji-kitchen-knife></span>
              <span><emoji-amphora></emoji-amphora></span>
              <span><emoji-globe-showing-europe-africa></emoji-globe-showing-europe-africa></span>
              <span><emoji-globe-showing-americas></emoji-globe-showing-americas></span>
              <span><emoji-globe-showing-asia-australia></emoji-globe-showing-asia-australia></span>
              <span><emoji-globe-with-meridians></emoji-globe-with-meridians></span>
              <span><emoji-world-map></emoji-world-map></span>
              <span><emoji-map-of-japan></emoji-map-of-japan></span>
              <span><emoji-compass></emoji-compass></span>
              <span><emoji-snow-capped-mountain></emoji-snow-capped-mountain></span>
              <span><emoji-mountain></emoji-mountain></span>
              <span><emoji-volcano></emoji-volcano></span>
              <span><emoji-mount-fuji></emoji-mount-fuji></span>
              <span><emoji-camping></emoji-camping></span>
              <span><emoji-beach-with-umbrella></emoji-beach-with-umbrella></span>
              <span><emoji-desert></emoji-desert></span>
              <span><emoji-desert-island></emoji-desert-island></span>
              <span><emoji-national-park></emoji-national-park></span>
              <span><emoji-stadium></emoji-stadium></span>
              <span><emoji-classical-building></emoji-classical-building></span>
              <span><emoji-building-construction></emoji-building-construction></span>
              <span><emoji-brick></emoji-brick></span>
              <span><emoji-rock></emoji-rock></span>
              <span><emoji-wood></emoji-wood></span>
              <span><emoji-hut></emoji-hut></span>
              <span><emoji-houses></emoji-houses></span>
              <span><emoji-derelict-house></emoji-derelict-house></span>
              <span><emoji-house></emoji-house></span>
              <span><emoji-house-with-garden></emoji-house-with-garden></span>
              <span><emoji-office-building></emoji-office-building></span>
              <span><emoji-japanese-post-office></emoji-japanese-post-office></span>
              <span><emoji-post-office></emoji-post-office></span>
              <span><emoji-hospital></emoji-hospital></span>
              <span><emoji-bank></emoji-bank></span>
              <span><emoji-hotel></emoji-hotel></span>
              <span><emoji-love-hotel></emoji-love-hotel></span>
              <span><emoji-convenience-store></emoji-convenience-store></span>
              <span><emoji-school></emoji-school></span>
              <span><emoji-department-store></emoji-department-store></span>
              <span><emoji-factory></emoji-factory></span>
              <span><emoji-japanese-castle></emoji-japanese-castle></span>
              <span><emoji-castle></emoji-castle></span>
              <span><emoji-wedding></emoji-wedding></span>
              <span><emoji-tokyo-tower></emoji-tokyo-tower></span>
              <span><emoji-statue-of-liberty></emoji-statue-of-liberty></span>
              <span><emoji-church></emoji-church></span>
              <span><emoji-mosque></emoji-mosque></span>
              <span><emoji-hindu-temple></emoji-hindu-temple></span>
              <span><emoji-synagogue></emoji-synagogue></span>
              <span><emoji-shinto-shrine></emoji-shinto-shrine></span>
              <span><emoji-kaaba></emoji-kaaba></span>
              <span><emoji-fountain></emoji-fountain></span>
              <span><emoji-tent></emoji-tent></span>
              <span><emoji-foggy></emoji-foggy></span>
              <span><emoji-night-with-stars></emoji-night-with-stars></span>
              <span><emoji-cityscape></emoji-cityscape></span>
              <span><emoji-sunrise-over-mountains></emoji-sunrise-over-mountains></span>
              <span><emoji-sunrise></emoji-sunrise></span>
              <span><emoji-cityscape-at-dusk></emoji-cityscape-at-dusk></span>
              <span><emoji-sunset></emoji-sunset></span>
              <span><emoji-bridge-at-night></emoji-bridge-at-night></span>
              <span><emoji-hot-springs></emoji-hot-springs></span>
              <span><emoji-carousel-horse></emoji-carousel-horse></span>
              <span><emoji-ferris-wheel></emoji-ferris-wheel></span>
              <span><emoji-roller-coaster></emoji-roller-coaster></span>
              <span><emoji-barber-pole></emoji-barber-pole></span>
              <span><emoji-circus-tent></emoji-circus-tent></span>
              <span><emoji-locomotive></emoji-locomotive></span>
              <span><emoji-railway-car></emoji-railway-car></span>
              <span><emoji-high-speed-train></emoji-high-speed-train></span>
              <span><emoji-bullet-train></emoji-bullet-train></span>
              <span><emoji-train></emoji-train></span>
              <span><emoji-metro></emoji-metro></span>
              <span><emoji-light-rail></emoji-light-rail></span>
              <span><emoji-station></emoji-station></span>
              <span><emoji-tram></emoji-tram></span>
              <span><emoji-monorail></emoji-monorail></span>
              <span><emoji-mountain-railway></emoji-mountain-railway></span>
              <span><emoji-tram-car></emoji-tram-car></span>
              <span><emoji-bus></emoji-bus></span>
              <span><emoji-oncoming-bus></emoji-oncoming-bus></span>
              <span><emoji-trolleybus></emoji-trolleybus></span>
              <span><emoji-minibus></emoji-minibus></span>
              <span><emoji-ambulance></emoji-ambulance></span>
              <span><emoji-fire-engine></emoji-fire-engine></span>
              <span><emoji-police-car></emoji-police-car></span>
              <span><emoji-oncoming-police-car></emoji-oncoming-police-car></span>
              <span><emoji-taxi></emoji-taxi></span>
              <span><emoji-oncoming-taxi></emoji-oncoming-taxi></span>
              <span><emoji-automobile></emoji-automobile></span>
              <span><emoji-oncoming-automobile></emoji-oncoming-automobile></span>
              <span><emoji-sport-utility-vehicle></emoji-sport-utility-vehicle></span>
              <span><emoji-pickup-truck></emoji-pickup-truck></span>
              <span><emoji-delivery-truck></emoji-delivery-truck></span>
              <span><emoji-articulated-lorry></emoji-articulated-lorry></span>
              <span><emoji-tractor></emoji-tractor></span>
              <span><emoji-racing-car></emoji-racing-car></span>
              <span><emoji-motorcycle></emoji-motorcycle></span>
              <span><emoji-motor-scooter></emoji-motor-scooter></span>
              <span><emoji-manual-wheelchair></emoji-manual-wheelchair></span>
              <span><emoji-motorized-wheelchair></emoji-motorized-wheelchair></span>
              <span><emoji-auto-rickshaw></emoji-auto-rickshaw></span>
              <span><emoji-bicycle></emoji-bicycle></span>
              <span><emoji-kick-scooter></emoji-kick-scooter></span>
              <span><emoji-skateboard></emoji-skateboard></span>
              <span><emoji-roller-skate></emoji-roller-skate></span>
              <span><emoji-bus-stop></emoji-bus-stop></span>
              <span><emoji-motorway></emoji-motorway></span>
              <span><emoji-railway-track></emoji-railway-track></span>
              <span><emoji-oil-drum></emoji-oil-drum></span>
              <span><emoji-fuel-pump></emoji-fuel-pump></span>
              <span><emoji-police-car-light></emoji-police-car-light></span>
              <span><emoji-horizontal-traffic-light></emoji-horizontal-traffic-light></span>
              <span><emoji-vertical-traffic-light></emoji-vertical-traffic-light></span>
              <span><emoji-stop-sign></emoji-stop-sign></span>
              <span><emoji-construction></emoji-construction></span>
              <span><emoji-anchor></emoji-anchor></span>
              <span><emoji-sailboat></emoji-sailboat></span>
              <span><emoji-canoe></emoji-canoe></span>
              <span><emoji-speedboat></emoji-speedboat></span>
              <span><emoji-passenger-ship></emoji-passenger-ship></span>
              <span><emoji-ferry></emoji-ferry></span>
              <span><emoji-motor-boat></emoji-motor-boat></span>
              <span><emoji-ship></emoji-ship></span>
              <span><emoji-airplane></emoji-airplane></span>
              <span><emoji-small-airplane></emoji-small-airplane></span>
              <span><emoji-airplane-departure></emoji-airplane-departure></span>
              <span><emoji-airplane-arrival></emoji-airplane-arrival></span>
              <span><emoji-parachute></emoji-parachute></span>
              <span><emoji-seat></emoji-seat></span>
              <span><emoji-helicopter></emoji-helicopter></span>
              <span><emoji-suspension-railway></emoji-suspension-railway></span>
              <span><emoji-mountain-cableway></emoji-mountain-cableway></span>
              <span><emoji-aerial-tramway></emoji-aerial-tramway></span>
              <span><emoji-satellite></emoji-satellite></span>
              <span><emoji-rocket></emoji-rocket></span>
              <span><emoji-flying-saucer></emoji-flying-saucer></span>
              <span><emoji-bellhop-bell></emoji-bellhop-bell></span>
              <span><emoji-luggage></emoji-luggage></span>
              <span><emoji-hourglass-done></emoji-hourglass-done></span>
              <span><emoji-hourglass-not-done></emoji-hourglass-not-done></span>
              <span><emoji-watch></emoji-watch></span>
              <span><emoji-alarm-clock></emoji-alarm-clock></span>
              <span><emoji-stopwatch></emoji-stopwatch></span>
              <span><emoji-timer-clock></emoji-timer-clock></span>
              <span><emoji-mantelpiece-clock></emoji-mantelpiece-clock></span>
              <span><emoji-twelve-thirty></emoji-twelve-thirty></span>
              <span><emoji-one-thirty></emoji-one-thirty></span>
              <span><emoji-two-thirty></emoji-two-thirty></span>
              <span><emoji-three-thirty></emoji-three-thirty></span>
              <span><emoji-four-thirty></emoji-four-thirty></span>
              <span><emoji-five-thirty></emoji-five-thirty></span>
              <span><emoji-six-thirty></emoji-six-thirty></span>
              <span><emoji-seven-thirty></emoji-seven-thirty></span>
              <span><emoji-eight-thirty></emoji-eight-thirty></span>
              <span><emoji-nine-thirty></emoji-nine-thirty></span>
              <span><emoji-ten-thirty></emoji-ten-thirty></span>
              <span><emoji-eleven-thirty></emoji-eleven-thirty></span>
              <span><emoji-new-moon></emoji-new-moon></span>
              <span><emoji-waxing-crescent-moon></emoji-waxing-crescent-moon></span>
              <span><emoji-first-quarter-moon></emoji-first-quarter-moon></span>
              <span><emoji-waxing-gibbous-moon></emoji-waxing-gibbous-moon></span>
              <span><emoji-full-moon></emoji-full-moon></span>
              <span><emoji-waning-gibbous-moon></emoji-waning-gibbous-moon></span>
              <span><emoji-last-quarter-moon></emoji-last-quarter-moon></span>
              <span><emoji-waning-crescent-moon></emoji-waning-crescent-moon></span>
              <span><emoji-crescent-moon></emoji-crescent-moon></span>
              <span><emoji-new-moon-face></emoji-new-moon-face></span>
              <span><emoji-first-quarter-moon-face></emoji-first-quarter-moon-face></span>
              <span><emoji-last-quarter-moon-face></emoji-last-quarter-moon-face></span>
              <span><emoji-thermometer></emoji-thermometer></span>
              <span><emoji-sun></emoji-sun></span>
              <span><emoji-full-moon-face></emoji-full-moon-face></span>
              <span><emoji-sun-with-face></emoji-sun-with-face></span>
              <span><emoji-ringed-planet></emoji-ringed-planet></span>
              <span><emoji-star></emoji-star></span>
              <span><emoji-glowing-star></emoji-glowing-star></span>
              <span><emoji-shooting-star></emoji-shooting-star></span>
              <span><emoji-milky-way></emoji-milky-way></span>
              <span><emoji-cloud></emoji-cloud></span>
              <span><emoji-sun-behind-cloud></emoji-sun-behind-cloud></span>
              <span><emoji-cloud-with-lightning-and-rain></emoji-cloud-with-lightning-and-rain></span>
              <span><emoji-sun-behind-small-cloud></emoji-sun-behind-small-cloud></span>
              <span><emoji-sun-behind-large-cloud></emoji-sun-behind-large-cloud></span>
              <span><emoji-sun-behind-rain-cloud></emoji-sun-behind-rain-cloud></span>
              <span><emoji-cloud-with-rain></emoji-cloud-with-rain></span>
              <span><emoji-cloud-with-snow></emoji-cloud-with-snow></span>
              <span><emoji-cloud-with-lightning></emoji-cloud-with-lightning></span>
              <span><emoji-tornado></emoji-tornado></span>
              <span><emoji-fog></emoji-fog></span>
              <span><emoji-wind-face></emoji-wind-face></span>
              <span><emoji-cyclone></emoji-cyclone></span>
              <span><emoji-rainbow></emoji-rainbow></span>
              <span><emoji-closed-umbrella></emoji-closed-umbrella></span>
              <span><emoji-umbrella></emoji-umbrella></span>
              <span><emoji-umbrella-with-rain-drops></emoji-umbrella-with-rain-drops></span>
              <span><emoji-umbrella-on-ground></emoji-umbrella-on-ground></span>
              <span><emoji-high-voltage></emoji-high-voltage></span>
              <span><emoji-snowflake></emoji-snowflake></span>
              <span><emoji-snowman></emoji-snowman></span>
              <span><emoji-snowman-without-snow></emoji-snowman-without-snow></span>
              <span><emoji-comet></emoji-comet></span>
              <span><emoji-fire></emoji-fire></span>
              <span><emoji-droplet></emoji-droplet></span>
              <span><emoji-water-wave></emoji-water-wave></span>
              <span><emoji-jack-o-lantern></emoji-jack-o-lantern></span>
              <span><emoji-christmas-tree></emoji-christmas-tree></span>
              <span><emoji-fireworks></emoji-fireworks></span>
              <span><emoji-sparkler></emoji-sparkler></span>
              <span><emoji-firecracker></emoji-firecracker></span>
              <span><emoji-sparkles></emoji-sparkles></span>
              <span><emoji-balloon></emoji-balloon></span>
              <span><emoji-party-popper></emoji-party-popper></span>
              <span><emoji-confetti-ball></emoji-confetti-ball></span>
              <span><emoji-tanabata-tree></emoji-tanabata-tree></span>
              <span><emoji-pine-decoration></emoji-pine-decoration></span>
              <span><emoji-japanese-dolls></emoji-japanese-dolls></span>
              <span><emoji-carp-streamer></emoji-carp-streamer></span>
              <span><emoji-wind-chime></emoji-wind-chime></span>
              <span><emoji-moon-viewing-ceremony></emoji-moon-viewing-ceremony></span>
              <span><emoji-red-envelope></emoji-red-envelope></span>
              <span><emoji-ribbon></emoji-ribbon></span>
              <span><emoji-wrapped-gift></emoji-wrapped-gift></span>
              <span><emoji-reminder-ribbon></emoji-reminder-ribbon></span>
              <span><emoji-admission-tickets></emoji-admission-tickets></span>
              <span><emoji-ticket></emoji-ticket></span>
              <span><emoji-military-medal></emoji-military-medal></span>
              <span><emoji-trophy></emoji-trophy></span>
              <span><emoji-sports-medal></emoji-sports-medal></span>
              <span><emoji-1st-place-medal></emoji-1st-place-medal></span>
              <span><emoji-2nd-place-medal></emoji-2nd-place-medal></span>
              <span><emoji-3rd-place-medal></emoji-3rd-place-medal></span>
              <span><emoji-soccer-ball></emoji-soccer-ball></span>
              <span><emoji-baseball></emoji-baseball></span>
              <span><emoji-softball></emoji-softball></span>
              <span><emoji-basketball></emoji-basketball></span>
              <span><emoji-volleyball></emoji-volleyball></span>
              <span><emoji-american-football></emoji-american-football></span>
              <span><emoji-rugby-football></emoji-rugby-football></span>
              <span><emoji-tennis></emoji-tennis></span>
              <span><emoji-flying-disc></emoji-flying-disc></span>
              <span><emoji-bowling></emoji-bowling></span>
              <span><emoji-cricket-game></emoji-cricket-game></span>
              <span><emoji-field-hockey></emoji-field-hockey></span>
              <span><emoji-ice-hockey></emoji-ice-hockey></span>
              <span><emoji-lacrosse></emoji-lacrosse></span>
              <span><emoji-ping-pong></emoji-ping-pong></span>
              <span><emoji-badminton></emoji-badminton></span>
              <span><emoji-boxing-glove></emoji-boxing-glove></span>
              <span><emoji-martial-arts-uniform></emoji-martial-arts-uniform></span>
              <span><emoji-goal-net></emoji-goal-net></span>
              <span><emoji-flag-in-hole></emoji-flag-in-hole></span>
              <span><emoji-ice-skate></emoji-ice-skate></span>
              <span><emoji-fishing-pole></emoji-fishing-pole></span>
              <span><emoji-diving-mask></emoji-diving-mask></span>
              <span><emoji-running-shirt></emoji-running-shirt></span>
              <span><emoji-skis></emoji-skis></span>
              <span><emoji-sled></emoji-sled></span>
              <span><emoji-curling-stone></emoji-curling-stone></span>
              <span><emoji-direct-hit></emoji-direct-hit></span>
              <span><emoji-yo-yo></emoji-yo-yo></span>
              <span><emoji-kite></emoji-kite></span>
              <span><emoji-pool-8-ball></emoji-pool-8-ball></span>
              <span><emoji-crystal-ball></emoji-crystal-ball></span>
              <span><emoji-magic-wand></emoji-magic-wand></span>
              <span><emoji-nazar-amulet></emoji-nazar-amulet></span>
              <span><emoji-video-game></emoji-video-game></span>
              <span><emoji-joystick></emoji-joystick></span>
              <span><emoji-slot-machine></emoji-slot-machine></span>
              <span><emoji-game-die></emoji-game-die></span>
              <span><emoji-puzzle-piece></emoji-puzzle-piece></span>
              <span><emoji-teddy-bear></emoji-teddy-bear></span>
              <span><emoji-nesting-dolls></emoji-nesting-dolls></span>
              <span><emoji-spade-suit></emoji-spade-suit></span>
              <span><emoji-heart-suit></emoji-heart-suit></span>
              <span><emoji-diamond-suit></emoji-diamond-suit></span>
              <span><emoji-club-suit></emoji-club-suit></span>
              <span><emoji-chess-pawn></emoji-chess-pawn></span>
              <span><emoji-joker></emoji-joker></span>
              <span><emoji-mahjong-red-dragon></emoji-mahjong-red-dragon></span>
              <span><emoji-flower-playing-cards></emoji-flower-playing-cards></span>
              <span><emoji-performing-arts></emoji-performing-arts></span>
              <span><emoji-framed-picture></emoji-framed-picture></span>
              <span><emoji-artist-palette></emoji-artist-palette></span>
              <span><emoji-thread></emoji-thread></span>
              <span><emoji-sewing-needle></emoji-sewing-needle></span>
              <span><emoji-yarn></emoji-yarn></span>
              <span><emoji-knot></emoji-knot></span>
              <span><emoji-glasses></emoji-glasses></span>
              <span><emoji-sunglasses></emoji-sunglasses></span>
              <span><emoji-goggles></emoji-goggles></span>
              <span><emoji-lab-coat></emoji-lab-coat></span>
              <span><emoji-safety-vest></emoji-safety-vest></span>
              <span><emoji-necktie></emoji-necktie></span>
              <span><emoji-t-shirt></emoji-t-shirt></span>
              <span><emoji-jeans></emoji-jeans></span>
              <span><emoji-scarf></emoji-scarf></span>
              <span><emoji-gloves></emoji-gloves></span>
              <span><emoji-coat></emoji-coat></span>
              <span><emoji-socks></emoji-socks></span>
              <span><emoji-dress></emoji-dress></span>
              <span><emoji-kimono></emoji-kimono></span>
              <span><emoji-sari></emoji-sari></span>
              <span><emoji-one-piece-swimsuit></emoji-one-piece-swimsuit></span>
              <span><emoji-briefs></emoji-briefs></span>
              <span><emoji-shorts></emoji-shorts></span>
              <span><emoji-bikini></emoji-bikini></span>
              <span><emoji-purse></emoji-purse></span>
              <span><emoji-handbag></emoji-handbag></span>
              <span><emoji-clutch-bag></emoji-clutch-bag></span>
              <span><emoji-shopping-bags></emoji-shopping-bags></span>
              <span><emoji-backpack></emoji-backpack></span>
              <span><emoji-thong-sandal></emoji-thong-sandal></span>
              <span><emoji-running-shoe></emoji-running-shoe></span>
              <span><emoji-hiking-boot></emoji-hiking-boot></span>
              <span><emoji-flat-shoe></emoji-flat-shoe></span>
              <span><emoji-high-heeled-shoe></emoji-high-heeled-shoe></span>
              <span><emoji-ballet-shoes></emoji-ballet-shoes></span>
              <span><emoji-crown></emoji-crown></span>
              <span><emoji-top-hat></emoji-top-hat></span>
              <span><emoji-graduation-cap></emoji-graduation-cap></span>
              <span><emoji-billed-cap></emoji-billed-cap></span>
              <span><emoji-military-helmet></emoji-military-helmet></span>
              <span><emoji-prayer-beads></emoji-prayer-beads></span>
              <span><emoji-lipstick></emoji-lipstick></span>
              <span><emoji-ring></emoji-ring></span>
              <span><emoji-gem-stone></emoji-gem-stone></span>
              <span><emoji-muted-speaker></emoji-muted-speaker></span>
              <span><emoji-speaker-low-volume></emoji-speaker-low-volume></span>
              <span><emoji-speaker-medium-volume></emoji-speaker-medium-volume></span>
              <span><emoji-speaker-high-volume></emoji-speaker-high-volume></span>
              <span><emoji-loudspeaker></emoji-loudspeaker></span>
              <span><emoji-megaphone></emoji-megaphone></span>
              <span><emoji-postal-horn></emoji-postal-horn></span>
              <span><emoji-bell></emoji-bell></span>
              <span><emoji-bell-with-slash></emoji-bell-with-slash></span>
              <span><emoji-musical-score></emoji-musical-score></span>
              <span><emoji-musical-note></emoji-musical-note></span>
              <span><emoji-musical-notes></emoji-musical-notes></span>
              <span><emoji-studio-microphone></emoji-studio-microphone></span>
              <span><emoji-level-slider></emoji-level-slider></span>
              <span><emoji-control-knobs></emoji-control-knobs></span>
              <span><emoji-microphone></emoji-microphone></span>
              <span><emoji-headphone></emoji-headphone></span>
              <span><emoji-radio></emoji-radio></span>
              <span><emoji-saxophone></emoji-saxophone></span>
              <span><emoji-accordion></emoji-accordion></span>
              <span><emoji-guitar></emoji-guitar></span>
              <span><emoji-musical-keyboard></emoji-musical-keyboard></span>
              <span><emoji-trumpet></emoji-trumpet></span>
              <span><emoji-violin></emoji-violin></span>
              <span><emoji-banjo></emoji-banjo></span>
              <span><emoji-drum></emoji-drum></span>
              <span><emoji-long-drum></emoji-long-drum></span>
              <span><emoji-mobile-phone></emoji-mobile-phone></span>
              <span><emoji-mobile-phone-with-arrow></emoji-mobile-phone-with-arrow></span>
              <span><emoji-telephone></emoji-telephone></span>
              <span><emoji-telephone-receiver></emoji-telephone-receiver></span>
              <span><emoji-pager></emoji-pager></span>
              <span><emoji-fax-machine></emoji-fax-machine></span>
              <span><emoji-battery></emoji-battery></span>
              <span><emoji-electric-plug></emoji-electric-plug></span>
              <span><emoji-laptop></emoji-laptop></span>
              <span><emoji-desktop-computer></emoji-desktop-computer></span>
              <span><emoji-printer></emoji-printer></span>
              <span><emoji-keyboard></emoji-keyboard></span>
              <span><emoji-computer-mouse></emoji-computer-mouse></span>
              <span><emoji-trackball></emoji-trackball></span>
              <span><emoji-computer-disk></emoji-computer-disk></span>
              <span><emoji-floppy-disk></emoji-floppy-disk></span>
              <span><emoji-optical-disk></emoji-optical-disk></span>
              <span><emoji-dvd></emoji-dvd></span>
              <span><emoji-abacus></emoji-abacus></span>
              <span><emoji-movie-camera></emoji-movie-camera></span>
              <span><emoji-film-frames></emoji-film-frames></span>
              <span><emoji-film-projector></emoji-film-projector></span>
              <span><emoji-clapper-board></emoji-clapper-board></span>
              <span><emoji-television></emoji-television></span>
              <span><emoji-camera></emoji-camera></span>
              <span><emoji-camera-with-flash></emoji-camera-with-flash></span>
              <span><emoji-video-camera></emoji-video-camera></span>
              <span><emoji-videocassette></emoji-videocassette></span>
              <span><emoji-magnifying-glass-tilted-left></emoji-magnifying-glass-tilted-left></span>
              <span><emoji-magnifying-glass-tilted-right></emoji-magnifying-glass-tilted-right></span>
              <span><emoji-candle></emoji-candle></span>
              <span><emoji-light-bulb></emoji-light-bulb></span>
              <span><emoji-flashlight></emoji-flashlight></span>
              <span><emoji-red-paper-lantern></emoji-red-paper-lantern></span>
              <span><emoji-diya-lamp></emoji-diya-lamp></span>
              <span><emoji-notebook-with-decorative-cover></emoji-notebook-with-decorative-cover></span>
              <span><emoji-closed-book></emoji-closed-book></span>
              <span><emoji-open-book></emoji-open-book></span>
              <span><emoji-green-book></emoji-green-book></span>
              <span><emoji-blue-book></emoji-blue-book></span>
              <span><emoji-orange-book></emoji-orange-book></span>
              <span><emoji-books></emoji-books></span>
              <span><emoji-notebook></emoji-notebook></span>
              <span><emoji-ledger></emoji-ledger></span>
              <span><emoji-page-with-curl></emoji-page-with-curl></span>
              <span><emoji-scroll></emoji-scroll></span>
              <span><emoji-page-facing-up></emoji-page-facing-up></span>
              <span><emoji-newspaper></emoji-newspaper></span>
              <span><emoji-rolled-up-newspaper></emoji-rolled-up-newspaper></span>
              <span><emoji-bookmark-tabs></emoji-bookmark-tabs></span>
              <span><emoji-bookmark></emoji-bookmark></span>
              <span><emoji-label></emoji-label></span>
              <span><emoji-money-bag></emoji-money-bag></span>
              <span><emoji-coin></emoji-coin></span>
              <span><emoji-yen-banknote></emoji-yen-banknote></span>
              <span><emoji-dollar-banknote></emoji-dollar-banknote></span>
              <span><emoji-euro-banknote></emoji-euro-banknote></span>
              <span><emoji-pound-banknote></emoji-pound-banknote></span>
              <span><emoji-money-with-wings></emoji-money-with-wings></span>
              <span><emoji-credit-card></emoji-credit-card></span>
              <span><emoji-receipt></emoji-receipt></span>
              <span><emoji-chart-increasing-with-yen></emoji-chart-increasing-with-yen></span>
              <span><emoji-envelope></emoji-envelope></span>
              <span><emoji-e-mail></emoji-e-mail></span>
              <span><emoji-incoming-envelope></emoji-incoming-envelope></span>
              <span><emoji-envelope-with-arrow></emoji-envelope-with-arrow></span>
              <span><emoji-outbox-tray></emoji-outbox-tray></span>
              <span><emoji-inbox-tray></emoji-inbox-tray></span>
              <span><emoji-package></emoji-package></span>
              <span><emoji-closed-mailbox-with-raised-flag></emoji-closed-mailbox-with-raised-flag></span>
              <span><emoji-closed-mailbox-with-lowered-flag></emoji-closed-mailbox-with-lowered-flag></span>
              <span><emoji-open-mailbox-with-raised-flag></emoji-open-mailbox-with-raised-flag></span>
              <span><emoji-open-mailbox-with-lowered-flag></emoji-open-mailbox-with-lowered-flag></span>
              <span><emoji-postbox></emoji-postbox></span>
              <span><emoji-ballot-box-with-ballot></emoji-ballot-box-with-ballot></span>
              <span><emoji-pencil></emoji-pencil></span>
              <span><emoji-black-nib></emoji-black-nib></span>
              <span><emoji-fountain-pen></emoji-fountain-pen></span>
              <span><emoji-pen></emoji-pen></span>
              <span><emoji-paintbrush></emoji-paintbrush></span>
              <span><emoji-crayon></emoji-crayon></span>
              <span><emoji-memo></emoji-memo></span>
              <span><emoji-briefcase></emoji-briefcase></span>
              <span><emoji-file-folder></emoji-file-folder></span>
              <span><emoji-open-file-folder></emoji-open-file-folder></span>
              <span><emoji-card-index-dividers></emoji-card-index-dividers></span>
              <span><emoji-calendar></emoji-calendar></span>
              <span><emoji-tear-off-calendar></emoji-tear-off-calendar></span>
              <span><emoji-spiral-notepad></emoji-spiral-notepad></span>
              <span><emoji-spiral-calendar></emoji-spiral-calendar></span>
              <span><emoji-card-index></emoji-card-index></span>
              <span><emoji-chart-increasing></emoji-chart-increasing></span>
              <span><emoji-chart-decreasing></emoji-chart-decreasing></span>
              <span><emoji-bar-chart></emoji-bar-chart></span>
              <span><emoji-clipboard></emoji-clipboard></span>
              <span><emoji-pushpin></emoji-pushpin></span>
              <span><emoji-round-pushpin></emoji-round-pushpin></span>
              <span><emoji-paperclip></emoji-paperclip></span>
              <span><emoji-linked-paperclips></emoji-linked-paperclips></span>
              <span><emoji-straight-ruler></emoji-straight-ruler></span>
              <span><emoji-triangular-ruler></emoji-triangular-ruler></span>
              <span><emoji-scissors></emoji-scissors></span>
              <span><emoji-card-file-box></emoji-card-file-box></span>
              <span><emoji-file-cabinet></emoji-file-cabinet></span>
              <span><emoji-wastebasket></emoji-wastebasket></span>
              <span><emoji-locked></emoji-locked></span>
              <span><emoji-unlocked></emoji-unlocked></span>
              <span><emoji-locked-with-pen></emoji-locked-with-pen></span>
              <span><emoji-locked-with-key></emoji-locked-with-key></span>
              <span><emoji-key></emoji-key></span>
              <span><emoji-old-key></emoji-old-key></span>
              <span><emoji-hammer></emoji-hammer></span>
              <span><emoji-axe></emoji-axe></span>
              <span><emoji-pick></emoji-pick></span>
              <span><emoji-hammer-and-pick></emoji-hammer-and-pick></span>
              <span><emoji-hammer-and-wrench></emoji-hammer-and-wrench></span>
              <span><emoji-dagger></emoji-dagger></span>
              <span><emoji-crossed-swords></emoji-crossed-swords></span>
              <span><emoji-pistol></emoji-pistol></span>
              <span><emoji-boomerang></emoji-boomerang></span>
              <span><emoji-bow-and-arrow></emoji-bow-and-arrow></span>
              <span><emoji-shield></emoji-shield></span>
              <span><emoji-carpentry-saw></emoji-carpentry-saw></span>
              <span><emoji-wrench></emoji-wrench></span>
              <span><emoji-screwdriver></emoji-screwdriver></span>
              <span><emoji-nut-and-bolt></emoji-nut-and-bolt></span>
              <span><emoji-gear></emoji-gear></span>
              <span><emoji-clamp></emoji-clamp></span>
              <span><emoji-balance-scale></emoji-balance-scale></span>
              <span><emoji-white-cane></emoji-white-cane></span>
              <span><emoji-link></emoji-link></span>
              <span><emoji-chains></emoji-chains></span>
              <span><emoji-hook></emoji-hook></span>
              <span><emoji-toolbox></emoji-toolbox></span>
              <span><emoji-magnet></emoji-magnet></span>
              <span><emoji-ladder></emoji-ladder></span>
              <span><emoji-alembic></emoji-alembic></span>
              <span><emoji-test-tube></emoji-test-tube></span>
              <span><emoji-petri-dish></emoji-petri-dish></span>
              <span><emoji-dna></emoji-dna></span>
              <span><emoji-microscope></emoji-microscope></span>
              <span><emoji-telescope></emoji-telescope></span>
              <span><emoji-satellite-antenna></emoji-satellite-antenna></span>
              <span><emoji-syringe></emoji-syringe></span>
              <span><emoji-drop-of-blood></emoji-drop-of-blood></span>
              <span><emoji-pill></emoji-pill></span>
              <span><emoji-adhesive-bandage></emoji-adhesive-bandage></span>
              <span><emoji-stethoscope></emoji-stethoscope></span>
              <span><emoji-door></emoji-door></span>
              <span><emoji-elevator></emoji-elevator></span>
              <span><emoji-mirror></emoji-mirror></span>
              <span><emoji-window></emoji-window></span>
              <span><emoji-bed></emoji-bed></span>
              <span><emoji-couch-and-lamp></emoji-couch-and-lamp></span>
              <span><emoji-chair></emoji-chair></span>
              <span><emoji-toilet></emoji-toilet></span>
              <span><emoji-plunger></emoji-plunger></span>
              <span><emoji-shower></emoji-shower></span>
              <span><emoji-bathtub></emoji-bathtub></span>
              <span><emoji-mouse-trap></emoji-mouse-trap></span>
              <span><emoji-razor></emoji-razor></span>
              <span><emoji-lotion-bottle></emoji-lotion-bottle></span>
              <span><emoji-safety-pin></emoji-safety-pin></span>
              <span><emoji-broom></emoji-broom></span>
              <span><emoji-basket></emoji-basket></span>
              <span><emoji-roll-of-paper></emoji-roll-of-paper></span>
              <span><emoji-bucket></emoji-bucket></span>
              <span><emoji-soap></emoji-soap></span>
              <span><emoji-toothbrush></emoji-toothbrush></span>
              <span><emoji-sponge></emoji-sponge></span>
              <span><emoji-fire-extinguisher></emoji-fire-extinguisher></span>
              <span><emoji-shopping-cart></emoji-shopping-cart></span>
              <span><emoji-cigarette></emoji-cigarette></span>
              <span><emoji-coffin></emoji-coffin></span>
              <span><emoji-headstone></emoji-headstone></span>
              <span><emoji-funeral-urn></emoji-funeral-urn></span>
              <span><emoji-moai></emoji-moai></span>
              <span><emoji-placard></emoji-placard></span>
              <span><emoji-atm-sign></emoji-atm-sign></span>
              <span><emoji-litter-in-bin-sign></emoji-litter-in-bin-sign></span>
              <span><emoji-potable-water></emoji-potable-water></span>
              <span><emoji-wheelchair-symbol></emoji-wheelchair-symbol></span>
              <span><emoji-restroom></emoji-restroom></span>
              <span><emoji-baby-symbol></emoji-baby-symbol></span>
              <span><emoji-water-closet></emoji-water-closet></span>
              <span><emoji-passport-control></emoji-passport-control></span>
              <span><emoji-customs></emoji-customs></span>
              <span><emoji-baggage-claim></emoji-baggage-claim></span>
              <span><emoji-left-luggage></emoji-left-luggage></span>
              <span><emoji-warning></emoji-warning></span>
              <span><emoji-children-crossing></emoji-children-crossing></span>
              <span><emoji-no-entry></emoji-no-entry></span>
              <span><emoji-prohibited></emoji-prohibited></span>
              <span><emoji-no-bicycles></emoji-no-bicycles></span>
              <span><emoji-no-smoking></emoji-no-smoking></span>
              <span><emoji-no-littering></emoji-no-littering></span>
              <span><emoji-non-potable-water></emoji-non-potable-water></span>
              <span><emoji-no-pedestrians></emoji-no-pedestrians></span>
              <span><emoji-no-mobile-phones></emoji-no-mobile-phones></span>
              <span><emoji-no-one-under-eighteen></emoji-no-one-under-eighteen></span>
              <span><emoji-radioactive></emoji-radioactive></span>
              <span><emoji-biohazard></emoji-biohazard></span>
              <span><emoji-up-arrow></emoji-up-arrow></span>
              <span><emoji-up-right-arrow></emoji-up-right-arrow></span>
              <span><emoji-right-arrow></emoji-right-arrow></span>
              <span><emoji-down-right-arrow></emoji-down-right-arrow></span>
              <span><emoji-down-arrow></emoji-down-arrow></span>
              <span><emoji-down-left-arrow></emoji-down-left-arrow></span>
              <span><emoji-left-arrow></emoji-left-arrow></span>
              <span><emoji-up-left-arrow></emoji-up-left-arrow></span>
              <span><emoji-up-down-arrow></emoji-up-down-arrow></span>
              <span><emoji-left-right-arrow></emoji-left-right-arrow></span>
              <span><emoji-right-arrow-curving-left></emoji-right-arrow-curving-left></span>
              <span><emoji-left-arrow-curving-right></emoji-left-arrow-curving-right></span>
              <span><emoji-right-arrow-curving-up></emoji-right-arrow-curving-up></span>
              <span><emoji-right-arrow-curving-down></emoji-right-arrow-curving-down></span>
              <span><emoji-clockwise-vertical-arrows></emoji-clockwise-vertical-arrows></span>
              <span><emoji-counterclockwise-arrows-button></emoji-counterclockwise-arrows-button></span>
              <span><emoji-back-arrow></emoji-back-arrow></span>
              <span><emoji-end-arrow></emoji-end-arrow></span>
              <span><emoji-soon-arrow></emoji-soon-arrow></span>
              <span><emoji-top-arrow></emoji-top-arrow></span>
              <span><emoji-place-of-worship></emoji-place-of-worship></span>
              <span><emoji-atom-symbol></emoji-atom-symbol></span>
              <span><emoji-om></emoji-om></span>
              <span><emoji-star-of-david></emoji-star-of-david></span>
              <span><emoji-wheel-of-dharma></emoji-wheel-of-dharma></span>
              <span><emoji-yin-yang></emoji-yin-yang></span>
              <span><emoji-latin-cross></emoji-latin-cross></span>
              <span><emoji-orthodox-cross></emoji-orthodox-cross></span>
              <span><emoji-star-and-crescent></emoji-star-and-crescent></span>
              <span><emoji-peace-symbol></emoji-peace-symbol></span>
              <span><emoji-menorah></emoji-menorah></span>
              <span><emoji-dotted-six-pointed-star></emoji-dotted-six-pointed-star></span>
              <span><emoji-aries></emoji-aries></span>
              <span><emoji-taurus></emoji-taurus></span>
              <span><emoji-gemini></emoji-gemini></span>
              <span><emoji-cancer></emoji-cancer></span>
              <span><emoji-leo></emoji-leo></span>
              <span><emoji-virgo></emoji-virgo></span>
              <span><emoji-libra></emoji-libra></span>
              <span><emoji-scorpio></emoji-scorpio></span>
              <span><emoji-sagittarius></emoji-sagittarius></span>
              <span><emoji-capricorn></emoji-capricorn></span>
              <span><emoji-aquarius></emoji-aquarius></span>
              <span><emoji-pisces></emoji-pisces></span>
              <span><emoji-ophiuchus></emoji-ophiuchus></span>
              <span><emoji-shuffle-tracks-button></emoji-shuffle-tracks-button></span>
              <span><emoji-repeat-button></emoji-repeat-button></span>
              <span><emoji-repeat-single-button></emoji-repeat-single-button></span>
              <span><emoji-play-button></emoji-play-button></span>
              <span><emoji-fast-forward-button></emoji-fast-forward-button></span>
              <span><emoji-next-track-button></emoji-next-track-button></span>
              <span><emoji-play-or-pause-button></emoji-play-or-pause-button></span>
              <span><emoji-reverse-button></emoji-reverse-button></span>
              <span><emoji-fast-reverse-button></emoji-fast-reverse-button></span>
              <span><emoji-last-track-button></emoji-last-track-button></span>
              <span><emoji-upwards-button></emoji-upwards-button></span>
              <span><emoji-fast-up-button></emoji-fast-up-button></span>
              <span><emoji-downwards-button></emoji-downwards-button></span>
              <span><emoji-fast-down-button></emoji-fast-down-button></span>
              <span><emoji-pause-button></emoji-pause-button></span>
              <span><emoji-stop-button></emoji-stop-button></span>
              <span><emoji-record-button></emoji-record-button></span>
              <span><emoji-eject-button></emoji-eject-button></span>
              <span><emoji-cinema></emoji-cinema></span>
              <span><emoji-dim-button></emoji-dim-button></span>
              <span><emoji-bright-button></emoji-bright-button></span>
              <span><emoji-antenna-bars></emoji-antenna-bars></span>
              <span><emoji-vibration-mode></emoji-vibration-mode></span>
              <span><emoji-mobile-phone-off></emoji-mobile-phone-off></span>
              <span><emoji-female-sign></emoji-female-sign></span>
              <span><emoji-male-sign></emoji-male-sign></span>
              <span><emoji-transgender-symbol></emoji-transgender-symbol></span>
              <span><emoji-multiply></emoji-multiply></span>
              <span><emoji-plus></emoji-plus></span>
              <span><emoji-minus></emoji-minus></span>
              <span><emoji-divide></emoji-divide></span>
              <span><emoji-infinity></emoji-infinity></span>
              <span><emoji-double-exclamation-mark></emoji-double-exclamation-mark></span>
              <span><emoji-exclamation-question-mark></emoji-exclamation-question-mark></span>
              <span><emoji-question-mark></emoji-question-mark></span>
              <span><emoji-white-question-mark></emoji-white-question-mark></span>
              <span><emoji-white-exclamation-mark></emoji-white-exclamation-mark></span>
              <span><emoji-exclamation-mark></emoji-exclamation-mark></span>
              <span><emoji-wavy-dash></emoji-wavy-dash></span>
              <span><emoji-currency-exchange></emoji-currency-exchange></span>
              <span><emoji-heavy-dollar-sign></emoji-heavy-dollar-sign></span>
              <span><emoji-medical-symbol></emoji-medical-symbol></span>
              <span><emoji-recycling-symbol></emoji-recycling-symbol></span>
              <span><emoji-fleur-de-lis></emoji-fleur-de-lis></span>
              <span><emoji-trident-emblem></emoji-trident-emblem></span>
              <span><emoji-name-badge></emoji-name-badge></span>
              <span><emoji-japanese-symbol-for-beginner></emoji-japanese-symbol-for-beginner></span>
              <span><emoji-hollow-red-circle></emoji-hollow-red-circle></span>
              <span><emoji-check-mark-button></emoji-check-mark-button></span>
              <span><emoji-check-box-with-check></emoji-check-box-with-check></span>
              <span><emoji-check-mark></emoji-check-mark></span>
              <span><emoji-cross-mark></emoji-cross-mark></span>
              <span><emoji-cross-mark-button></emoji-cross-mark-button></span>
              <span><emoji-curly-loop></emoji-curly-loop></span>
              <span><emoji-double-curly-loop></emoji-double-curly-loop></span>
              <span><emoji-part-alternation-mark></emoji-part-alternation-mark></span>
              <span><emoji-eight-spoked-asterisk></emoji-eight-spoked-asterisk></span>
              <span><emoji-eight-pointed-star></emoji-eight-pointed-star></span>
              <span><emoji-sparkle></emoji-sparkle></span>
              <span><emoji-copyright></emoji-copyright></span>
              <span><emoji-registered></emoji-registered></span>
              <span><emoji-trade-mark></emoji-trade-mark></span>
              <span><emoji-input-latin-uppercase></emoji-input-latin-uppercase></span>
              <span><emoji-input-latin-lowercase></emoji-input-latin-lowercase></span>
              <span><emoji-input-numbers></emoji-input-numbers></span>
              <span><emoji-input-symbols></emoji-input-symbols></span>
              <span><emoji-input-latin-letters></emoji-input-latin-letters></span>
              <span><emoji-cl-button></emoji-cl-button></span>
              <span><emoji-cool-button></emoji-cool-button></span>
              <span><emoji-free-button></emoji-free-button></span>
              <span><emoji-information></emoji-information></span>
              <span><emoji-id-button></emoji-id-button></span>
              <span><emoji-circled-m></emoji-circled-m></span>
              <span><emoji-new-button></emoji-new-button></span>
              <span><emoji-ng-button></emoji-ng-button></span>
              <span><emoji-ok-button></emoji-ok-button></span>
              <span><emoji-p-button></emoji-p-button></span>
              <span><emoji-sos-button></emoji-sos-button></span>
              <span><emoji-vs-button></emoji-vs-button></span>
              <span><emoji-red-circle></emoji-red-circle></span>
              <span><emoji-orange-circle></emoji-orange-circle></span>
              <span><emoji-yellow-circle></emoji-yellow-circle></span>
              <span><emoji-green-circle></emoji-green-circle></span>
              <span><emoji-blue-circle></emoji-blue-circle></span>
              <span><emoji-purple-circle></emoji-purple-circle></span>
              <span><emoji-brown-circle></emoji-brown-circle></span>
              <span><emoji-black-circle></emoji-black-circle></span>
              <span><emoji-white-circle></emoji-white-circle></span>
              <span><emoji-red-square></emoji-red-square></span>
              <span><emoji-orange-square></emoji-orange-square></span>
              <span><emoji-yellow-square></emoji-yellow-square></span>
              <span><emoji-green-square></emoji-green-square></span>
              <span><emoji-blue-square></emoji-blue-square></span>
              <span><emoji-purple-square></emoji-purple-square></span>
              <span><emoji-brown-square></emoji-brown-square></span>
              <span><emoji-black-large-square></emoji-black-large-square></span>
              <span><emoji-white-large-square></emoji-white-large-square></span>
              <span><emoji-black-medium-square></emoji-black-medium-square></span>
              <span><emoji-white-medium-square></emoji-white-medium-square></span>
              <span><emoji-black-medium-small-square></emoji-black-medium-small-square></span>
              <span><emoji-white-medium-small-square></emoji-white-medium-small-square></span>
              <span><emoji-black-small-square></emoji-black-small-square></span>
              <span><emoji-white-small-square></emoji-white-small-square></span>
              <span><emoji-large-orange-diamond></emoji-large-orange-diamond></span>
              <span><emoji-large-blue-diamond></emoji-large-blue-diamond></span>
              <span><emoji-small-orange-diamond></emoji-small-orange-diamond></span>
              <span><emoji-small-blue-diamond></emoji-small-blue-diamond></span>
              <span><emoji-red-triangle-pointed-up></emoji-red-triangle-pointed-up></span>
              <span><emoji-red-triangle-pointed-down></emoji-red-triangle-pointed-down></span>
              <span><emoji-diamond-with-a-dot></emoji-diamond-with-a-dot></span>
              <span><emoji-radio-button></emoji-radio-button></span>
              <span><emoji-white-square-button></emoji-white-square-button></span>
              <span><emoji-black-square-button></emoji-black-square-button></span>
              <span><emoji-chequered-flag></emoji-chequered-flag></span>
              <span><emoji-triangular-flag></emoji-triangular-flag></span>
              <span><emoji-crossed-flags></emoji-crossed-flags></span>
              <span><emoji-black-flag></emoji-black-flag></span>
              <span><emoji-white-flag></emoji-white-flag></span>
      </div>   
    </div>
  </div>
</div>


<div id="picker-button" class="flex">
    <span>
        <div style='position:absolute;font-size:10px;transform:translate(-50%, -50%);left:50%;bottom:50%;white-space:nowrap;'>Emoji &#x25bc;</div>
    </span>
</div>


`;

//consts

class HabitatEmojiPicker extends HTMLElement {

   constructor() {
    super();

    this.attachShadow({ mode: 'open' });
    this.shadowRoot.append(TEMPLATE.content.cloneNode(true));

    this.pickerBtn = this.shadowRoot.querySelector('#picker-button');
    this.popover = this.shadowRoot.querySelector('#emoji-popover');
    this.selector = this.shadowRoot.querySelector('#emoji-select');

    this.pickerBtn.addEventListener('click', (evt) => {
        evt.stopPropagation();
        this.popover.classList.toggle('active');
    });


    this.selector.addEventListener('click', evt => {
        if (evt.target.tagName.startsWith('EMOJI-')) {
            const span = this.shadowRoot.querySelector('#picker-button span');
            const emoji = document.createElement(`${evt.target.tagName}`);
            span.replaceChildren(emoji);
        }
    }, true);  
   }
  
  //functions
}
customElements.define('habitat-emoji-picker', HabitatEmojiPicker);